@baseUrl = https://localhost:5001

# @name getAllCustomers
GET {{baseUrl}}/customers

###

# @name createCustomer
POST {{baseUrl}}/customers
Content-Type: application/json

{
    "fullName": "Dingeman Damen",
    "email": "kevin.d.damen@gmail.com",
    "gitHubUserName": "GamiDroid",
    "dateOfBirth": "1996-12-03T00:00:00"
}

###

# @name getCustomerById
@customerId = 583da162-2a8c-4d61-aaeb-0f74ff0aca5b
GET {{baseUrl}}/customers/{{customerId}}

###

# @name updateCustomer
@customerId = 583da162-2a8c-4d61-aaeb-0f74ff0aca5b
PUT {{baseUrl}}/customers/{{customerId}} HTTP/1.1
Content-Type: application/json

{
    "fullName": "Kevin Dingeman Damen",
    "email": "kevin.d.damen@gmail.com",
    "gitHubUserName": "GamiDroid",
    "dateOfBirth": "1996-12-03T00:00:00"
}

###

# @name deleteCustomer
@customerId = {{createCustomer.response.body.$.id}}
DELETE {{baseUrl}}/customers/{{customerId}}